### ISSUE TITLE
MGC assumes input is a data matrix

### ISSUE THREAD

**Issue by tpsatish95** [neurodata/mgcpy#123]
Perform check if the input is a data matrix or distance matrix before calling the `compute_distance_matrix` function.

**Comment by junhaobearxiong** [comment]
Need to make sure the data type of the distance matrix is some type of float, otherwise `local_correlations` throws error like
`ValueError: Buffer dtype mismatch, expected 'float_t' but got 'long'`

**Comment by junhaobearxiong** [comment]
HHG doesn't actually use `compute_distance_matrix`, but uses the scipy function `distance_matrix`
