### ISSUE TITLE
distance transform?

### ISSUE THREAD

**Issue by jovo** [neurodata/mgcpy#126]
- seems like https://mgcpy.readthedocs.io/en/latest/mgcpy.independence_tests.mgc.html#module-mgcpy.independence_tests.mgc.distance_transform
is in the wrong place, should be in utils?

- also, https://mgcpy.readthedocs.io/en/latest/mgcpy.independence_tests.mdmr.html#module-mgcpy.independence_tests.mdmr.mdmrfunctions 
includes computing distances, shouldn't that also be in utils?

- also, what is "Gower's centered similarity matrix"? define how you are centering. is it the same as in dcorr and mgc?

**Comment by sampan501** [comment]
> * seems like https://mgcpy.readthedocs.io/en/latest/mgcpy.independence_tests.mgc.html#module-mgcpy.independence_tests.mgc.distance_transform
>   is in the wrong place, should be in utils?

https://github.com/neurodata/mgcpy/pull/127/commits/6adec47def3c6a18f7406ab481fd13501c3e2aff



> * also, https://mgcpy.readthedocs.io/en/latest/mgcpy.independence_tests.mdmr.html#module-mgcpy.independence_tests.mdmr.mdmrfunctions
>   includes computing distances, shouldn't that also be in utils?

https://github.com/neurodata/mgcpy/pull/127/commits/6adec47def3c6a18f7406ab481fd13501c3e2aff



> * also, what is "Gower's centered similarity matrix"? define how you are centering. is it the same as in dcorr and mgc?

This centering process is different from DCorr and MGC
https://github.com/neurodata/mgcpy/blob/61a0f14d589aa659201f434807c86dba38f9f7a4/mgcpy/independence_tests/utils/mdmr_functions.py#L65
